library_portal/library/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^index/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^login/$', views.login_page, name='login'),
    url(r'^register/$', views.register_page, name='register'),
    url(r'^registration_success/(?P<name>\w+)/$', views.registration_success, name='registration_success'),
    url(r'^register_func/$', views.register_func, name='register_func'),
    url(r'^login_func/$', views.login_func, name='login_func'),
    url(r'^logout/$', views.logout_func, name='logout'),
    url(r'^index/add_book/$',views.add_book_page,name="add_book_page"),
    url(r'^index/add_book_func/$',views.add_book_func,name="add_book_func"),
    url(r'^index/(?P<book_id>[0-9]+)/edit_book_page/$',views.edit_book_page,name="edit_book_page"),
    url(r'^index/(?P<book_id>[0-9]+)/edit_book_func/$',views.edit_book_func,name="edit_book_func"),
    url(r'^index/(?P<book_id>[0-9]+)/delete_book_page/$',views.delete_book_page,name="delete_book_page"),
    url(r'^index/(?P<book_id>[0-9]+)/delete_book_func/$',views.delete_book_func,name="delete_book_func"),
    url(r'^index/(?P<book_id>[0-9]+)/request_book/$',views.request_book,name="request_book"),
    url(r'^index/(?P<book_id>[0-9]+)/return_book/$',views.return_book,name="return_book"),
]

library_portal/library_portal/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^library/', include('library.urls',namespace="library")),
    url(r'^admin/', include(admin.site.urls)),
]

library_portal/library/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.utils import timezone
# Create your models here.

class Book(models.Model):
	book_title=models.CharField(max_length=200)
	publisher=models.CharField(max_length=200)
	author=models.CharField(max_length=200)
	date_added=models.DateTimeField('Date Added')
	total_number=models.IntegerField(default=0)
	total_lent=models.IntegerField(default=0)
	def available(self):
		return self.total_lent<self.total_number
	def __unicode__(self):
		return self.book_title

	class Meta:
		permissions=(("request_book","customer can request books"),("return_book","customer can return book"))

class Customer(models.Model):
	user=models.OneToOneField(User)
	book_borrowed=models.ForeignKey(Book,null=True)
	user.user_permissions=["request_book","return_book"]
	def __unicode__(self):
		return self.user.first_name
	
class Librarian(models.Model):
	user=models.OneToOneField(User)
	user.user_permissions=["add_book","change_book","delete_book"]
	def __unicode__(self):
		return self.user.first_name
	

library_portal/library/views.py
from django.shortcuts import render,redirect
from .models import Book, Customer, Librarian
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.views import generic
from django.utils import timezone
# Create your views here.

class IndexView(generic.ListView):
	
	template_name = 'library/index.html'
	context_object_name = 'book_list'

	def get_queryset(self):
		return Book.objects.order_by('book_title')

class DetailView(generic.DetailView):

    model = Book
    template_name = 'library/detail.html'

def welcome(request):
	if request.user.is_authenticated() == True:
		return redirect('/library/index')
	return render(request,'library/welcome.html')

def login_page(request):
	return render(request,'library/login.html')

def register_page(request):
	return render(request,'library/register.html')

def registration_success(request,name):
	context={'name':name}
	return render(request,'library/registration_success.html',context) 

def register_func(request):
	u=User.objects.create_user(first_name=request.POST['first_name'],last_name=request.POST['last_name'],username=request.POST['user_name'],password=request.POST['password'])
	u.save()
	if request.POST['user_type']=="L":
		lib=Librarian(user=u)
		lib.save()
	elif request.POST['user_type']=="C":
		cust=Customer(user=u)
		cust.save()
	
	return HttpResponseRedirect(reverse('library:registration_success',args=(u.first_name,)))

def login_func(request):
	username=request.POST['user_name']
	password=request.POST['password']
	user=authenticate(username=username, password=password)
	if user is not None:
		login(request,user)
		return HttpResponseRedirect('/library/index')			
	else:
		return HttpResponse('Wrong username or password. <a href="/library/login">Try again</a>.')

def logout_func(request):
	logout(request)
	return redirect('/library/welcome')

def add_book_page(request):
	return render(request,'library/add_book.html')

def add_book_func(request):
	b=Book(book_title=request.POST['book_title'],publisher=request.POST['publisher'],author=request.POST['author'],date_added=timezone.now(),total_number=request.POST['total_num'])
	b.save()
	return redirect('/library/index')

def edit_book_page(request,book_id):
	book=Book.objects.get(pk=book_id)
	return render(request,'library/edit_book.html',{'book':book})

def edit_book_func(request,book_id):
	b=Book.objects.get(pk=book_id)
	b.book_title=request.POST['book_title']
	b.author=request.POST['author']
	b.publisher=request.POST['publisher']
	b.total_number=request.POST['total_num']
	b.save()
	return HttpResponseRedirect(reverse('library:detail',args=(book_id)))

def delete_book_page(request,book_id):
	book=Book.objects.get(pk=book_id)
	return render(request,'library/delete_book.html',{'book_id':book_id})

def delete_book_func(request,book_id):
	book=Book.objects.get(pk=book_id)
	book.delete()
	return redirect('/library/index')	

def request_book(request,book_id):
	book=Book.objects.get(pk=book_id)
	if request.user.customer.book_borrowed is not None:
		return HttpResponse("You have already requested one book! You can't request more till you return what you have taken!!")
	else:
		book.total_lent+=1
		book.save()
		request.user.customer.book_borrowed=book
		request.user.customer.save()
		return HttpResponseRedirect(reverse('library:detail',args=(book_id)))

def return_book(request,book_id):
	book=Book.objects.get(pk=book_id)
	if request.user.customer.book_borrowed == book:
		book.total_lent-=1
		book.save()
		request.user.customer.book_borrowed=None
		request.user.customer.save()
		return HttpResponseRedirect(reverse('library:detail',args=(book_id)))	

library_portal/library/templates/library/add_book.html
{% if request.user.is_authenticated == True and request.user.librarian %}
<h1>Add Book</h1>
<form action="{% url 'library:add_book_func' %}" method="post">
{% csrf_token %}
<label for="title">Book Title:</label>
<input type="text" name="book_title" id="title" />
<br><br>
<label for="author">Author:</label>
<input type="text" name="author" id="author" />
<br><br>
<label for="publisher">Publisher</label>
<input type="text" name="publisher" id="publisher" />
<br><br>
<label for="number">Total number:</label>
<input type="number" name="total_num" id="number" min="0" />
<br><br>
<input type="submit" value="Submit" />
</form>
{% else %}
	<h2>You have to <a href="{% url 'library:welcome' %}">login</a> as a librarian to access this page</h2>
{% endif %}

library_portal/library/templates/library/delete_book.html
{% if request.user.is_authenticated == True and request.user.librarian %}
Are you sure you want to completely delete this book from the library? This will remove <b>all</b> references of this book from the library.<br><br><br>
<a href="{% url 'library:detail' book_id %}"><input type="button" value="No" /></a>
<a href="{% url 'library:delete_book_func' book_id %}"><input type="button" value="Yes" /></a>
{% endif %}

library_portal/library/templates/library/detail.html
{% if request.user.is_authenticated == True%}
	<h1>{{ book.book_title }}</h1>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<ul>
	        <li><h4>Author:</h4>{{ book.author }}</li>
	        <li><h4>Publisher:</h4>{{ book.publisher }}</li>
	        <li><h4>Date added:</h4>{{ book.date_added }}</li>
	        <li><h4>Total number of copies:</h4>{{ book.total_number }}</li>
	       	<li><h4>Available:</h4>{% if book.available == True %} Yes {% else %} No {% endif %}</li>
	</ul>
	<br><br>
	{% if request.user.librarian %}
		<a href="{% url 'library:edit_book_page' book.id %}"><input type="button" value="Edit Book" /></a>
		<a href="{% url 'library:delete_book_page' book.id %}"><input type="button" value="Delete Book" /></a>
	{% elif request.user.customer %}
		{% if request.user.customer.book_borrowed.id == book.id %}
			<a href="{% url 'library:return_book' book.id %}"><input type="button" value="Return this book"></a><br>
		{% elif book.available == True %}
			<a href="{% url 'library:request_book' book.id %}"><input type="button" value="Request this Book"></a><br>
		{% endif %}
	{% endif %}
	<br><br><br>
	<a href="{% url 'library:logout' %}">Log out</a>
{% else %}
	<h2>You have to <a href="{% url 'library:welcome' %}">login</a> to access this page</h2>
{% endif %}

library_portal/library/templates/library/edit_book.html
{% if request.user.is_authenticated == True and request.user.librarian and book %}
<h1>Edit Book</h1>
<form action="{% url 'library:edit_book_func' book.id %}" method="post">
{% csrf_token %}
<label for="title">Book Title:</label>
<input type="text" name="book_title" id="title" value="{{book.book_title}}" />
<br><br>
<label for="author">Author:</label>
<input type="text" name="author" id="author" value="{{book.author}}" />
<br><br>
<label for="publisher">Publisher</label>
<input type="text" name="publisher" id="publisher" value="{{book.publisher}}" />
<br><br>
<label for="number">Total number:</label>
<input type="number" name="total_num" id="number" min="0" value="{{book.total_number}}"/>
<br><br>
<pre><input type="submit" value="Save Changes" />		<a href="{% url 'library:detail' book.id %}"><input type="button" value="Discard changes"/></a></pre>
</form>
<br><br><br>
<a href="{% url 'library:logout' %}">Log out</a>
{% else %}
	<h2>You have to <a href="{% url 'library:welcome' %}">login</a> to access this page</h2>
{% endif %}

library_portal/library/templates/library/index.html
{% if request.user.is_authenticated == True %}
	<h1>Book List</h1>
	<h3>Hi {{request.user.first_name}}</h3>
	{% if book_list %}
	    <table border="1px solid black">
	    <tr>
	    	<th>Title</th>
	    	<th>Author</th>
	    	<th>Date Added</th>
	    </tr>
	    {% for book in book_list %}
	        <tr>
	        <td><a href="{% url 'library:detail' book.id %}">{{ book.book_title }}</a></td>
	        <td>{{ book.author }}</td>
	        <td>{{ book.date_added }}</td>
	        </tr>
	    {% endfor %}
	    </table>
	{% else %}
	    <p>No books are available.</p>
	{% endif %}
	{% if request.user.librarian %}	
			<a href="{% url 'library:add_book_page' %}"><input type="button" value="Add new Book"/></a>
	{% endif %}
	<br><br><br>
	<a href="{% url 'library:logout' %}">Log out</a>
{% else %}
	<h2>You have to <a href="{% url 'library:welcome' %}">login</a> to access this page</h2>
{% endif %}

library_portal/library/templates/library/login.html
{% if request.user.is_authenticated != True %} 
<h1>Login</h1>
<form action="{% url 'library:login_func' %}" method="post">
{% csrf_token %}
<label for="username">Username:</label>
<input type="text" name="user_name" id="username" /><br><br><br>
<label for="password">Password:</label>
<input type="password" name="password" id="password" /><br><br>
<input type="submit" value="Submit" />
</form>
{% else %}
<h1> You are already logged in, {{request.user.first_name}}! </h1>
If you want to log-in from another account, click <a href="{% url 'library:logout' %}">here</a>.
{% endif %}

library_portal/library/templates/library/register.html
<h1>Registration</h1>
<form action="{% url 'library:register_func' %}" method="post">
{% csrf_token %}
<label>User Type:</label><br><br>
<input type="radio" name="user_type" id="lib" value="L">
<label for="lib">Librarian</label>
<input type="radio" name="user_type" id="cust" value="C" checked>
<label for="cust">Customer</label>
<br><br>
<label for="first">First Name:</label>
<input type="text" name="first_name" id="first" />
<br><br>
<label for="last">Last Name:</label>
<input type="text" name="last_name" id="last" />
<br><br>
<label for="user_name">Username:</label>
<input type="text" name="user_name" id="user_name" />
<br><br>
<label for="pass">Password:</label>
<input type="password" name="password" id="pass" />
<br><br>
<input type="submit" value="Submit" />
</form>

library_portal/library/templates/library/registration_success.html
<h1> Registration Successful!!</h1>

<h3> You have successfully registered {{name}}</h3>

Click here to <a href="{% url 'library:login' %}">Login</a>

library_portal/library/templates/library/welcome.html
<html>
<h1>Welcome to the library</h1>
<br>
<br>
<h3><a href="{% url 'library:login' %}">Login</a></h3>
<h3><a href="{% url 'library:register' %}">Register</a></h3>
</html>